# Inspired by https://docs.docker.com/compose/django/
version: '3'

services:
  db:
    # NOTE: No persistance storage configured.
    # See: https://hub.docker.com/_/postgres/
    image: postgres
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  redis:
    image: redis

  web:
    image: maykinmedia/record-management-app:latest
    environment: &web_env
      - DJANGO_SETTINGS_MODULE=rma.conf.docker
      - ALLOWED_HOSTS=*
      - DEBUG=True
      - CACHE_DEFAULT=redis:6379/0
      - CACHE_AXES=redis:6379/0
      - CACHE_OAS=redis:6379/1
      - SECRET_KEY=${SECRET_KEY:-145cqii@)+z$b&9dcmdctpm+&be1#9zslxm+x)0+u*^qf!qz(6}
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis

  celery:
    image: maykinmedia/record-management-app:latest
    environment: *web_env
    command: /celery_worker.sh
    depends_on:
      - db
      - redis
